### ISSUE TITLE
Initialise server using hapi

### ISSUE THREAD

**Issue by minaorangina** [globetown/crushlines#1]
![screen shot 2016-01-11 at 19 57 05](https://cloud.githubusercontent.com/assets/8915092/12244864/836c2256-b89d-11e5-8e17-1cfb84d1ce21.png)

**Comment by heron2014** [comment]
Problem was issued here: [L11](https://github.com/globetown/crushlines/blob/init/lib/index.js#L11). 
```
server.connection is an method which takes an object as argument

server.connection({port:port})

```
